### ISSUE TITLE
Cannot call (gdscript) object's methods from lua

### ISSUE THREAD

**Issue by al0fdf** [gilzoide/lua-gdextension#45] opened 2024-12-06 07:28 UTC
When creating a class in godot, I cannot use `lua.globals` to make the class accessible from lua

**Reproduction**
Create and run a new scene with the below script:
```
extends Node2D

class SomeClass:
	func _init(from_gd=false):
		if from_gd:
			print("Init was called from gd")
		else:
			print("Init was called from lua")
	
	func some_method():
		print("Some other method was called")

func _ready():
	var lua = LuaState.new()
	lua.open_libraries()
	
	var c = SomeClass.new(true)
	lua.globals["SomeClass"] = c
	
	var result = lua.do_string("""
	SomeClass()
	SomeClass:some_method()
	""")
	
	if result is LuaError:
		printerr("Error in Lua code: ", result)
	else:
		print("LUA result is ", result)
```

When running the code, the following error is seen:

```
Init was called from gd
  Error in Lua code: [string "..."]:2: attempt to call a RefCounted value
  stack traceback:
  	[C]: in global 'SomeClass'
  	[string "..."]:2: in main chunk
```

**Expected behavior**
Calling `SomeClass()` from lua would call the init method, and calling `SomeClass:some_method()` would call the object's `some_method` method.

**Environment:**
 - Godot version: v4.2
 - Module version: v0.1.0 from https://godotengine.org/asset-library/asset/2330

**Additional details**

The init function can be called when setting `lua.globals["SomeClass"] = c._init`, however, when using this, `some_method` is not recognized as valid:

```
Init was called from gd
Init was called from lua
  Error in Lua code: [string "..."]:3: attempt to call a nil value (method 'some_method')
  stack traceback:
  	[string "..."]:3: in main chunk
```

**Comment by gilzoide** [comment] 2024-12-06 09:58
Hey @al0fdf , thanks for the report.

When you do `lua.globals["SomeClass"] = c`, in Lua `SomeClass` doesn't refer to your class, but rather to `c`, which is an instance of your class that you created in the line above `var c = SomeClass.new(true)`.
That's why the error message in your first attempt is `attempt to call a RefCounted value`, because you're trying to call a value that is actually an instance of your class and not the class itself.

When you do `lua.globals["SomeClass"] = c._init`, now `SomeClass` refers to the Callable `c._init`. Callables don't have a definition for `some_method`, that's why you get the next error `attempt to call a nil value (method 'some_method')`.

If you want to properly create instances from Lua, you do just like in GDScript: call `SomeClass:new(...)`.
This only works if the class name is registered in ClassDB, when `ClassDB.class_exists("SomeClass")`. I don't know if nested classes, like SomeClass in your GDScript there, would work. In case it doesn't , moving the class to a separate script and giving it a `class_name` should do the trick.

Another thing about object initialization: just like in GDScript, you never call `_init` yourself, it gets called automatically from `new(...)`.

**Comment by gilzoide** [comment] 2024-12-21 10:31
I'm closing this issue, since the problem is in your script. Feel free to open a new Issue or Discussion for other problems/questions.

**Closed by gilzoide** 2024-12-21 10:31 UTC
